name: SonarQube Frontend Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  SonarQube-Frontend-Scan:
    runs-on: [self-hosted]

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: SQ Frontend Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner -X